export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_DOWNLOAD_PRODUCTS = "START_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const DELETED_PRODUCT_SUCCESS = "DELETED_PRODUCT_SUCCESS";
export const DELETED_PRODUCT_ERROR = "DELETED_PRODUCT_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_PRODUCT_EDITION = "START_PRODUCT_EDITION";
export const EDITED_PRODUCT_SUCCESS = "EDITED_PRODUCT_SUCCESS";
export const EDITED_PRODUCT_ERROR = "EDITED_PRODUCT_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
